const products = [
  {
    id: "sofa-patagonia",
    nombre: "Sofá Patagonia",
    categoria: "Living",
    precio: 1200000,
    imagen: "sofa-patagonia.png",
    alt: "Sofá Patagonia de tres cuerpos de madera noble con cojines de plumón reciclado",
    descripcionCorta: "Confort amplio y líneas atemporales en madera noble.",
    destacado: true,
  },
  {
    id: "butaca-mendoza",
    nombre: "Butaca Mendoza",
    categoria: "Living",
    precio: 450000,
    imagen: "butaca-mendoza.png",
    alt: "Butaca Mendoza tapizada en bouclé Rosa Polvoriento con base giratoria de guatambú macizo",
    descripcionCorta: "Diseño envolvente con base giratoria de guatambú.",
    destacado: true,
  },
  {
    id: "mesa-de-centro-araucaria",
    nombre: "Mesa de Centro Araucaria",
    categoria: "Living",
    precio: 680000,
    imagen: "mesa-de-centro-araucaria.png",
    alt: "Mesa de centro Araucaria con tapa circular de mármol Patagonia y base de nogal macizo",
    descripcionCorta: "Mármol Patagonia y nogal macizo en armonía.",
    destacado: true,
  },
  {
    id: "aparador-uspallata",
    nombre: "Aparador Uspallata",
    categoria: "Comedor",
    precio: 890000,
    imagen: "aparador-uspallata.png",
    alt: "Aparador Uspallata de madera con puertas de listones",
    descripcionCorta: "Guardado generoso con una presencia serena y cálida.",
    destacado: false,
  },
  {
    id: "biblioteca-recoleta",
    nombre: "Biblioteca Recoleta",
    categoria: "Guardado",
    precio: 760000,
    imagen: "biblioteca-recoleta.png",
    alt: "Biblioteca Recoleta modular de madera con estantes abiertos",
    descripcionCorta: "Composición modular para ordenar y exhibir tus objetos.",
    destacado: false,
  },
  {
    id: "escritorio-costa",
    nombre: "Escritorio Costa",
    categoria: "Trabajo",
    precio: 540000,
    imagen: "escritorio-costa.png",
    alt: "Escritorio Costa de madera con cajón y pasacables",
    descripcionCorta: "Superficie amplia y proporciones pensadas para concentrarte.",
    destacado: false,
  },
  {
    id: "mesa-comedor-pampa",
    nombre: "Mesa de Comedor Pampa",
    categoria: "Comedor",
    precio: 980000,
    imagen: "mesa-comedor-pampa.png",
    alt: "Mesa de comedor Pampa de madera maciza para seis personas",
    descripcionCorta: "Una mesa generosa para compartir todos los días.",
    destacado: true,
  },
  {
    id: "mesa-de-noche-aconcagua",
    nombre: "Mesa de Noche Aconcagua",
    categoria: "Dormitorio",
    precio: 280000,
    imagen: "mesa-de-noche-aconcagua.png",
    alt: "Mesa de noche Aconcagua de madera con un cajón y estante inferior",
    descripcionCorta: "Una pieza compacta con espacio para lo esencial.",
    destacado: false,
  },
  {
    id: "silla-de-trabajo-belgrano",
    nombre: "Silla de Trabajo Belgrano",
    categoria: "Trabajo",
    precio: 360000,
    imagen: "silla-de-trabajo-belgrano.png",
    alt: "Silla de trabajo Belgrano con respaldo de madera curvada y asiento tapizado",
    descripcionCorta: "Ergonomía y materiales nobles para jornadas largas.",
    destacado: false,
  },
  {
    id: "sillas-cordoba",
    nombre: "Sillas Córdoba",
    categoria: "Comedor",
    precio: 190000,
    imagen: "sillas-cordoba.png",
    alt: "Sillas Córdoba de comedor en madera clara con asiento de fibra trenzada",
    descripcionCorta: "Silueta liviana y resistencia para reunirse alrededor de la mesa.",
    destacado: false,
  },
  {
    id: "sillon-copacabana",
    nombre: "Sillón Copacabana",
    categoria: "Living",
    precio: 620000,
    imagen: "sillon-copacabana.png",
    alt: "Sillón Copacabana tapizado de volumen amplio con patas de madera",
    descripcionCorta: "Un refugio personal de volumen amable y tacto suave.",
    destacado: false,
  },
];

module.exports = products;
